apiVersion: 1

datasources:
  - name: BBS Postgres
    uid: bbs-postgres
    type: postgres
    access: proxy
    url: $POSTGRES_HOST
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: $POSTGRES_SSLMODE
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: false
